/* Survival Deutschland v1.5.0 · local vector overview and assets */
const CACHE='survival-nrw-v1.5.0';const FILES=["./","./regen.webp","./haselnuss.webp","./fish.webp","./kochen.webp","./fell.webp","./brennnessel.webp","./fa\u0308hrten.webp","./knot-bund.webp","./bundeslaender_karte.js","./wild_150.js","./README.txt","./manifest.webmanifest","./knot-rund.webp","./kamille.webp","./index.html","./styles.css","./filter.webp","./orientierung.webp","./app.js","./v13_gpx.js","./feuer.webp","./regions_data.js","./wild_vogel.webp","./knoten.webp","./erstehilfe.webp","./lo\u0308wenzahn.webp","./lager.webp","./wild_hase.webp","./heilkraut.webp","./icon-512.png","./brombeere.webp","./schutz_folie.webp","./knot-spann.webp","./knot-achter.webp","./wild_fleisch.webp","./data.js","./unterkunft_150.js","./v13_data.js","./icon-192.png","./schafgarbe.webp","./wild_vorbereitung.webp","./knoten_data.js","./wild_schwein.webp","./foraging.webp","./unterstand.webp","./schutz_tarp.webp","./knot-palstek.webp","./laubhu\u0308tte.webp","./schutz_laub.webp","./spitzwegerich.webp","./kleinwild.webp","./silberweide.webp","./holunder.webp","./wild_reh.webp","./wild_kochen.webp","./schutz_liege.webp","./version.json","./knot-mastwurf.webp","./sw.js"];
self.addEventListener('install',event=>event.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(FILES.map(p=>c.add(p)));await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{await Promise.all((await caches.keys()).filter(k=>k.startsWith('survival-nrw-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==self.location.origin)return;
 if(u.pathname.endsWith('/version.json')){e.respondWith(fetch(e.request,{cache:'no-store'}));return}
 if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put('./index.html',r.clone())).catch(()=>{});return r}).catch(()=>caches.match('./index.html')));return}
 e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone())).catch(()=>{});return r}))) });
