'use strict';
/* Add-on: user-supplied GPX or GeoJSON track viewer, no remote tiles */
const nrwRouteGet=()=>{try{return JSON.parse(localStorage.getItem('survival-nrw:track'))}catch{return null}};
function gpxPage(){return `${pageTitle('Eigene Routen · offline','GPX & GeoJSON','GPS-Koordinaten aus einer selbst importierten Linie schematisch anzeigen. Kein Kartenmaterial oder Routing enthalten.')}
<div class="notice warning">Die Zeichnung ist KEINE Wanderkarte. Wege, Brücken, Höhen, Gelände, Gefahren und Sperrungen fehlen. GPS ist ungenau. Für Navigation und Rettung geeignete Offline-Karten, Kompass und amtliche Hinweise nutzen.</div>
<div class="save-card"><h3>Route importieren</h3><label class="upload-label">GPX oder GeoJSON auswählen<input id="gpx-upload" type="file" accept=".gpx,.geojson,.json,application/gpx+xml,application/geo+json"></label><p class="tiny muted">Bis 2 MB, maximal 3000 dargestellte Punkte; Import und Speicherung nur lokal.</p><div id="gpx-message" role="status" class="notice">${nrwRouteGet()?'Gespeicherte Route wird angezeigt.':'Noch keine Route geladen.'}</div></div>
<div id="gpx-display" class="track-display" role="img" aria-label="Schematische Trackdarstellung"></div><div class="toolrow"><button class="btn secondary small" data-action="gpx-gps">Eigene Position anzeigen</button><button class="btn outline small" data-action="gpx-delete">Route entfernen</button></div><p id="gpx-gps-out" class="tiny muted">Die Position wird nicht gespeichert.</p><a href="#/karten" class="btn outline small">Meine Karten und Wegpunkte →</a>`}
function plotGPX(points,gps){let el=document.getElementById('gpx-display');if(!el)return;if(!points?.length){el.innerHTML='<div class="empty">Importiere eine GPX- oder GeoJSON-Datei, um die Linie zu sehen.</div>';return}
let lng=points.map(p=>p[0]),lat=points.map(p=>p[1]);let x0=Math.min(...lng),x1=Math.max(...lng),y0=Math.min(...lat),y1=Math.max(...lat),dx=Math.max(x1-x0,.0005),dy=Math.max(y1-y0,.0005);x0-=dx*.1;x1+=dx*.1;y0-=dy*.1;y1+=dy*.1;
let coord=p=>[Math.round(30+(p[0]-x0)/(x1-x0)*700),Math.round(347-(p[1]-y0)/(y1-y0)*310)],c=points.map(coord);
let d=c.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');let mark='';if(gps){let p=coord(gps);if(p[0]>=24&&p[0]<=738&&p[1]>=30&&p[1]<=350)mark=`<circle cx="${p[0]}" cy="${p[1]}" r="8" fill="#ffbe62" stroke="white" stroke-width="3"/>`}
el.innerHTML=`<svg viewBox="0 0 760 380" role="img" aria-label="Darstellung von ${points.length} Koordinaten" xmlns="http://www.w3.org/2000/svg"><rect width="760" height="380" rx="16" fill="#13271e"/>${[1,2,3,4].map(n=>`<path d="M0 ${n*76} H760 M${n*152} 0 V380" stroke="#355040" stroke-width="1"/>`).join('')}<path d="${d}" stroke="#c7e6a5" fill="none" stroke-width="4" stroke-linecap="round"/><circle cx="${c[0][0]}" cy="${c[0][1]}" r="6" fill="white"/><circle cx="${c.at(-1)[0]}" cy="${c.at(-1)[1]}" r="6" fill="#f7ae50"/>${mark}<text x="22" y="28" fill="#e0eadb" font-size="15">Schematische Linie · kein Kartenhintergrund</text></svg><p class="tiny muted">${points.length} Trackpunkte. Start: weiß, Ende: orange. Zusätzlicher gelber Punkt: GPS, soweit im Ausschnitt.</p>`}
function parseGPX(fileText,fileName){let pts=[];if(fileName.toLowerCase().endsWith('.gpx')){let xml=new DOMParser().parseFromString(fileText,'application/xml');if(xml.querySelector('parsererror'))throw Error('Ungültiges GPX-XML');let rows=[...xml.querySelectorAll('trkpt')];if(!rows.length)rows=[...xml.querySelectorAll('rtept')];pts=rows.map(p=>[Number(p.getAttribute('lon')),Number(p.getAttribute('lat'))]);}
else {let obj=JSON.parse(fileText);function read(g){if(!g)return;if(g.type==='FeatureCollection')return g.features.forEach(read);if(g.type==='Feature')return read(g.geometry);if(g.type==='LineString')return pts.push(...g.coordinates);if(g.type==='MultiLineString')return g.coordinates.forEach(line=>pts.push(...line))}read(obj)}
pts=pts.filter(p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(Number(p[0]))&&Number.isFinite(Number(p[1]))&&Math.abs(Number(p[0]))<=180&&Math.abs(Number(p[1]))<=90).map(p=>[Number(p[0]),Number(p[1])]);if(pts.length<2)throw Error('Keine gültigen Trackpunkte');const stride=Math.ceil(pts.length/3000),sample=pts.filter((_,i)=>i%stride===0);if(sample.at(-1).toString()!==pts.at(-1).toString())sample.push(pts.at(-1));return sample}
function bindGPXListeners(){
 document.addEventListener('change',async e=>{if(e.target.id!=='gpx-upload')return;let f=e.target.files?.[0],el=document.getElementById('gpx-message');if(!f||!el)return;try{if(f.size>2*1024*1024)throw Error('Datei über 2 MB');let p=parseGPX(await f.text(),f.name);let persisted=true;try{localStorage.setItem('survival-nrw:track',JSON.stringify(p))}catch{persisted=false}plotGPX(p);el.textContent=persisted?`${p.length} Koordinatenpunkte gespeichert.`:`${p.length} Punkte angezeigt; lokales Speichern in diesem Browser nicht erlaubt.`}catch(err){el.textContent='Import fehlgeschlagen: '+(err.message||err)}});
 document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='gpx-delete'){try{localStorage.removeItem('survival-nrw:track')}catch{}plotGPX(null);document.getElementById('gpx-message').textContent='Track entfernt.'}if(b.dataset.action==='gpx-gps'){let out=document.getElementById('gpx-gps-out');if(!navigator.geolocation){out.textContent='GPS nicht unterstützt.';return}out.textContent='Standort wird bestimmt …';navigator.geolocation.getCurrentPosition(p=>{out.textContent=`GPS: ${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)} (±${Math.round(p.coords.accuracy)} m)`;plotGPX(nrwRouteGet(),[p.coords.longitude,p.coords.latitude])},()=>out.textContent='GPS nicht verfügbar. Standortberechtigung prüfen.',{enableHighAccuracy:true,timeout:15000})}})
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindGPXListeners,{once:true});else bindGPXListeners();
