'use strict';
/* Survival Deutschland 1.5.0: bundled state outlines, GPS point, shelter reference & wild hygiene.
   State geometries manually reduced from isellsoap/deutschlandGeoJSON (public domain/Unlicense).
   NOT a surveyed street map or a replacement for officially published topographic maps. */
const V15_SHELTERS=[
{id:'tarp',name:'Tarp-A-Frame',image:'shelter-tarp',best:'Plane · wechselnder Wind',time:'15–35 Min. als Übung',materials:['Wasserfeste Plane','Stabile Abspannleine','Heringe / geeignete Verankerungen','Trockene Schlafunterlage'],steps:['Sichere, leicht erhöhte Stelle ohne Totholz und ohne Sturz-/Hochwassergefahr wählen.','Zwei Verankerungspunkte auf passender Höhe auswählen und eine straffe Firstleine spannen.','Plane mittig über die Firstleine legen; Nähte und Öffnungen berücksichtigen.','Seiten bodennah und mit gleichmäßiger Spannung abspannen.','Windabgewandten Einstieg und ausreichend Bodenisolierung einrichten.','Konstruktion bei Wetterwechsel kontrollieren und nachspannen.'],caution:'Nie offenes Feuer im Tarp. Bäume nicht beschädigen; Übernachten im Wald kann verboten sein.'},
{id:'lean',name:'Lean-to / Schrägdach',image:'shelter-leaf',best:'Windschutz bei gleichbleibender Windrichtung',time:'1–3 Std. als Übung',materials:['Liegende Äste','Stabiler Querholm','Lose dünne Äste','Plane oder vorhandene lose Blätter'],steps:['Standplatz auf trockenem, festem Boden und ohne Astbruchgefahr auswählen.','Stabilen Querholm sicher in Astgabeln oder freistehenden Stützen auflegen.','Dachrippen schräg gegen den Querholm stellen, Abstände eng halten.','Mit kleineren Ästen quer stabilisieren und nur lose vorhandenes Material als Abdeckung nutzen.','Schlafplatz durch eine dicke trockene Unterlage vom Boden isolieren.','Konstruktion aus allen Richtungen auf Kippgefahr und freie Belüftung prüfen.'],caution:'Nur Windschutz; bei Seitenregen kann Nässe eindringen. Nicht unter geschützten/lebenden Gehölzen bauen.'},
{id:'laub',name:'Laubhütte / Debris-Hut',image:'laubhütte',best:'Naturmaterial bei Kälte ohne Plane',time:'Mehrere Stunden',materials:['Tragfähiger Firstast','Dünnere abgestorbene Äste','Sehr viel trockenes loses Laub','Trockenes Bodenmaterial'],steps:['Geschützten Platz oberhalb von Mulden und außerhalb von Hochwasserzonen suchen.','Firststange bodennah mit standsicherem Auflager befestigen.','Dicht an dicht Rippen in einem A-Rahmen anlegen.','Dünnes Reisig querlegen, sodass Laub nicht durchrutscht.','Beide Seiten mit möglichst dicker lockerer Laubschicht bedecken.','Eingang klein und windabgewandt, Schlafplatz gut belüftet und trocken gestalten.'],caution:'Weder zuverlässig wasserdicht noch sicher warm. Keine lebenden Bäume fällen oder sensible Lebensräume zerstören.'},
{id:'zweipunkt',name:'Tarp-Schrägdach',image:'unterstand',best:'Schneller Regenschutz, viel Kopffreiheit',time:'10–20 Min. als Übung',materials:['Tarp','Abspannleine','Zwei bis vier Befestigungspunkte'],steps:['Oberseite im Windschatten an stabilen, zulässigen Befestigungen fixieren.','Gegenüberliegende Seite tiefer ausrichten, damit Regen abfließen kann.','Ecken abspannen, ohne scharfe Kanten oder scheuernde Leinen.','Wasserablauf und Windseite auf Leckage prüfen.','Trockene Unterlage vom Dachabfluss entfernt platzieren.'],caution:'Offene Seiten bieten wenig Schutz bei Seitenwind und Kälte.'},
{id:'notfolie',name:'Rettungsdecken-Windschutz',image:'shelter-emergency',best:'Kurzfristiger Wind-/Regenschutz',time:'5–15 Min.',materials:['Rettungsdecke oder feste Folie','Leine, Schnur oder Clips','Trockene isolierende Unterlage'],steps:['Vorhandenen Windschatten suchen, etwa an einem sicheren niedrigen Erdwall.','Folie so ausrichten, dass der Wind nicht daruntergreift.','Ecken nur mit schonenden Befestigungen fixieren; Folie reißt leicht.','Person über trockene Kleidung und Unterlage isolieren.','Luftaustausch sicherstellen und Folie nicht dicht über Gesicht oder offene Flamme bringen.'],caution:'Folie hat kaum mechanische Stabilität. Kein Feuer und keine luftdichte Einhausung.'},
{id:'poncho',name:'Poncho-Kurzunterstand',image:'shelter-tarp',best:'Leichter Unterschlupf auf Tour',time:'10–20 Min.',materials:['Großer Poncho','Vier Abspannpunkte','Leine oder leichte Stäbe'],steps:['Poncho im geschützten Gelände auffalten und Saum begutachten.','Eine Längskante etwas höher befestigen; andere Kante tief zum Boden führen.','Vier Ecken mit angemessener Spannung sichern.','Belüftung, Regenabfluss und Abstand von Bodenpfützen prüfen.','Boden separat isolieren und Einstieg im Lee planen.'],caution:'Kleiner Innenraum, wenig Schutz bei Sturm und Kälte.'},
{id:'totholz',name:'Kleiner Reisig-Windschirm',image:'shelter-leaf',best:'Kurze Pause bei böigem Wind',time:'20–60 Min.',materials:['Lose liegende Zweige','Zwei standsichere Stützen','Optional Plane'],steps:['Sicheres Gelände mit natürlichen Hindernissen und Fluchtweg wählen.','Zwei stabile niedrige Auflagen oder Stützen setzen.','Lose abgestorbene Zweige schräg oder quer als Windwand schichten.','Gegen seitliches Wegrollen absichern und keinen schweren Aufbau über Personen errichten.','Im Lee Sitzelement oder Rettungsdecke verwenden.'],caution:'Kein Schlafschutz bei Starkregen; Brandlasten in trockenen Wäldern vermeiden.'},
{id:'bett',name:'Bodenisolation / niedrige Liege',image:'shelter-bed',best:'Nassen Boden isolieren',time:'20–90 Min.',materials:['Trockene Matte / Plane','Lose trockene Pflanzenreste','Bei Bedarf liegende dünne Hölzer'],steps:['Flache Stelle von spitzen Steinen und verrottetem Holz freimachen.','Wasserdichte oder feuchteresistente Unterlage ausbreiten.','Zusätzliche Dämmung aus sauberem trockenem Material aufbringen.','Schlafsack/Decke so platzieren, dass keine Wärmebrücken entstehen.','Auf Feuchtigkeit kontrollieren, bei Durchfeuchtung frühzeitig wechseln.'],caution:'Erhöhte improvisierte Betten können zusammenbrechen; ebenerdige Dämmung ist meist sicherer.'},
{id:'schnee',name:'Schneewand als Windschutz',image:'shelter-emergency',best:'Winter im Mittelgebirge',time:'15–45 Min.',materials:['Verdichtbarer Schnee','Schaufel oder improvisiertes Räumwerkzeug','Plane / warme Ausrüstung'],steps:['Lawinen-, Wechten- und Baumsturzgefahr ausschließen.','Niedrige Wand auf festem ebenem Untergrund anlegen.','Blöcke oder verdichteten Schnee nur niedrig und standfest stapeln.','Windschutz mit separater Plane kombinieren.','Belüftung sicherstellen und Wand auf Risse oder Instabilität prüfen.'],caution:'Keine Schneehöhle oder verschlossene Schneeunterkunft ohne Ausbildung. Erstickungs-/Einsturzgefahr.'},
{id:'natuerlich',name:'Natürlicher Windschatten',image:'shelter-leaf',best:'Schnell ohne Umbauten',time:'5–10 Min.',materials:['Sichere natürliche Geländeform','Rettungsdecke','Isolierende Sitz-/Liegeunterlage'],steps:['Geschützte Stelle hinter intakter Geländekante oder niedrigem Hügel suchen.','Abstand zu Felshängen, losen Blöcken und Gewässern einhalten.','Nicht unter kranken Bäumen oder instabilen Hangteilen verweilen.','Boden gegen Kälte isolieren, winddichten Mantel oder Folie nutzen.','Rettungsweg, Mobilfunk und Standortkenntnis erhalten.'],caution:'Höhlen und Felsüberhänge können Steinschlag, Tiere oder Hochwasser bergen. Nicht darin schlafen, wenn Lage ungeklärt.'}
];
const V15_WILD=[
{id:'reh',name:'Reh (Rehwild)',latin:'Capreolus capreolus',image:'wild-reh',facts:'Schalenwild; lebt häufig an Waldkanten, Lichtungen und in Feldfluren.',traces:'Typisch sind zwei schmale Schalenabdrücke. Form und Größe hängen von Boden, Tempo und Alter ab; keine sichere Einzelspur-Bestimmung.',warning:'Nur rechtmäßig erlegtes, unauffälliges und veterinärrechtlich zulässiges Wildbret verwenden.',pieces:['Rücken','Keulen','Schulter/Blatt','Hals','Rippenabschnitte'],steps:[['Herkunft und Gesundheitszustand','Rechtmäßige Herkunft, Auffälligkeiten und Freigaben kontrollieren. Bei krankhaft wirkendem Wild: nicht verwenden.','wild-reh'],['Schutz und Sauberkeit','Einmalhandschuhe anlegen, getrennte saubere Messer und eine desinfizierbare Arbeitsfläche vorbereiten.','kleinwild'],['Fachgerechtes Aufbrechen','Unter fachkundiger Anleitung die Körperhöhle schonend öffnen, ohne Magen oder Darm zu verletzen. Organe prüfen lassen; keine kontaminierten Teile verwenden.','kleinwild'],['Sicher und rasch kühlen','Wildkörper zügig hygienisch abkühlen und dauerhaft gekühlt lagern; Wärme- und Zeitverlauf kontrollieren.','fell'],['Aus der Decke schlagen','Fell mit sauberen Hilfsmitteln lösen; Haarseite und Fleischflächen voneinander fernhalten.','fell'],['Grob zerwirken','Keulen, Rücken und Schulter anatomisch sauber trennen; Messer und Unterlage währenddessen reinigen.','wild-reh'],['Küche: Rehschmorgericht','Geeignete Fleischstücke im sauberen Topf anbraten, mit Gemüse und Flüssigkeit langsam schmoren und sicher durchgaren. Kerntemperatur mit Thermometer prüfen.','kochen']],cook:'Rehragout: gewürfeltes, hygienisch gewonnenes Rehfleisch mit Zwiebeln und Gemüse anbraten, mit Brühe langsam schmoren. Garzustand und Temperatur prüfen.'},
{id:'schwein',name:'Wildschwein (Schwarzwild)',latin:'Sus scrofa',image:'wild-schwein',facts:'Wehrhaftes Schalenwild; lebenden Tieren, insbesondere Bachen mit Frischlingen, nicht nähern.',traces:'Breitere zweischalige Fährten; Afterklauen können im weichen Boden zusätzlich abgedrückt sein.',warning:'Vor jeglicher Verwendung ist die vorgeschriebene amtliche Trichinenuntersuchung mit negativem Ergebnis erforderlich. Niemals roh probieren.',pieces:['Nacken','Schulter','Rücken','Keule','Bauch'],steps:[['Rechtmäßigkeit und Freigaben','Nur rechtmäßig gewonnenes Wild nach erforderlichen Untersuchungen weiterverarbeiten. Keine Verwendung ohne negatives Trichinenergebnis.','wild-schwein'],['Sauberen Arbeitsplatz einrichten','Handschuhe, trennbare Werkzeuge, Reinigungs- und Kühlmöglichkeit vorhalten. Kein Kontakt zu Schmutzwasser.','kleinwild'],['Wildkörper fachgerecht versorgen','Magen-Darm-Bereich von Fleischoberflächen getrennt halten, Auffälligkeiten erkennen und bei Veränderungen zuständige Fachstelle einschalten.','kleinwild'],['Sorgfältige Kühlung','Geeignete hygienische Kühlung ohne Unterbrechung sicherstellen, Temperatur regelmäßig prüfen.','fell'],['Schwarte trennen und zerwirken','Nach Freigabe Schwarte und Fleisch durch geschultes Personal trennen; auf saubere Schnittführung achten.','wild-schwein'],['Teilstücke sortieren','Nacken, Schulter, Rücken, Bauch und Keule voneinander trennen und verpacken; konsequent gekühlt halten.','wild-schwein'],['Küche: Wildschweinbraten','Fleisch mit Wurzelgemüse zugedeckt schmoren und vollständig durchgaren. Rohwurst und halbrohe Produkte vermeiden.','kochen']],cook:'Wildschwein-Schmorbraten: aus freigegebenem Fleisch, Gemüse und Brühe zubereiten; vollständig garen, Kerntemperatur prüfen. Nicht roh kosten.'},
{id:'hase',name:'Feldhase',latin:'Lepus europaeus',image:'wild-hase',facts:'Offenlandbewohner; der Feldhase hat längere Ohren und kräftige Hinterläufe.',traces:'Sprungspur: oft zwei größere Hinterfußabdrücke vor den kleineren Vorderfußabdrücken. Einzelne Formen sind nicht eindeutig.',warning:'Tularämie (Hasenpest) möglich. Kranke oder tot gefundene Hasen niemals berühren oder verarbeiten. Bei Fieber nach Kontakt ärztliche Hilfe.',pieces:['Keulen','Rücken','Schultern','Vorderläufe'],steps:[['Herkunft und Krankheitszeichen','Nur legal erlegtes gesund erscheinendes Tier berücksichtigen. Bei ungewöhnlichem Verhalten oder Veränderungen: Abstand und Fachberatung.','wild-hase'],['Handschutz und Hygiene','Mit Handschuhen und sauberen Werkzeugen arbeiten; kein Kontakt von Körperflüssigkeiten mit Wunden oder Schleimhäuten.','kleinwild'],['Fachkundig versorgen','Bei fachlicher Ausbildung Haut und Bauchraum schonend eröffnen, innere Organe kontrollieren und Magen-Darm-Inhalt von Fleisch fernhalten.','kleinwild'],['Fell abziehen','Fell und saubere Fleischoberfläche strikt getrennt behandeln; Hände und Arbeitsmittel regelmäßig reinigen.','kleinwild'],['Schnell kühlen','Fleisch rasch auf sichere Lagertemperatur bringen und Kühlkette einhalten.','wild-hase'],['Teilstücke trennen','Rücken, Keulen und Schultern nach professionellem Schema auslösen.','wild-hase'],['Küche: geschmorte Hasenkeule','Mit Gemüse und Brühe zugedeckt schmoren, bis das Fleisch vollständig durchgegart ist; Thermometer verwenden.','kochen']],cook:'Hasenkeule: mit Zwiebel, Möhren und Brühe schonend schmoren; nur vollständig gegart servieren.'},
{id:'voegel',name:'Wildvögel (je nach Art)',latin:'z. B. Fasan, Wildente',image:'wild-vogel',facts:'Arten unterscheiden sich stark; Schutz- und Jagdstatus sind regional und saisonal verschieden.',traces:'Krallenspuren und Federfunde sind allein für eine eindeutige Artenbestimmung häufig ungeeignet.',warning:'Vogelgrippe möglich. Kranke oder tote Wildvögel nicht anfassen. Nur rechtmäßig gewonnene und gesundheitlich unauffällige Tiere verwenden.',pieces:['Brust','Keulen','Flügel'],steps:[['Art und Rechtmäßigkeit prüfen','Art zuverlässig bestimmen und Jagd-, Schonzeit- und Schutzregeln prüfen. Geschützte Vögel niemals verwenden.','wild-vogel'],['Krankheitsrisiken beurteilen','Keine verendeten oder krank wirkenden Wildvögel aufnehmen. Bei Verdacht auf Vogelgrippe Veterinärbehörde informieren.','wild-vogel'],['Hygienisch vorbereiten','Handschuhe, getrennte Messer und leicht zu reinigende Fläche verwenden; Staub und Aerosole möglichst vermeiden.','kleinwild'],['Federkleid entfernen','Nur ausgebildete Personen rupfen oder häuten Wildgeflügel unter hygienischen Bedingungen.','wild-vogel'],['Fachgerecht ausnehmen','Organe sorgfältig entfernen, ohne Darminhalt zu verteilen; bei Auffälligkeiten entsorgen beziehungsweise untersuchen lassen.','kleinwild'],['Rasch kühlen und zerlegen','Brust, Keulen und Flügel sauber trennen, getrennt verpacken und gekühlt lagern.','wild-vogel'],['Küche: geschmortes Wildgeflügel','Fleisch von Wildgeflügel vollständig durchgaren; rohes Fleisch strikt von verzehrfertigen Speisen trennen.','kochen']],cook:'Wildgeflügel mit Wurzelgemüse: nur freigegebenes Fleisch verwenden, im Ofen oder geschlossenen Topf vollständig garen. Kreuzkontamination verhindern.'}
];
let v15MapState={scale:1,centerX:405,centerY:405,gps:null,gpsWatch:null};
function v15ViewBox(){const d=800/v15MapState.scale;return `${v15MapState.centerX-d/2} ${v15MapState.centerY-d/2} ${d} ${d}`;}
function v15StateRegion(id){return (window.SURVIVAL_REGIONS||[]).find(r=>r.id===id)}
function offlineGermanyMap(){const boundaries=window.SURVIVAL_BOUNDARIES||{};
 const states=(window.SURVIVAL_REGIONS||[]).map(r=>`<option value="${r.id}" ${r.id===currentRegion().id?'selected':''}>${esc(r.name)}</option>`).join('');
 const shapes=Object.entries(boundaries).map(([k,d])=>`<a href="#/bundesland/${k}" aria-label="${esc(v15StateRegion(k)?.name||k)}"><path d="${d}" class="v15-state ${k===currentRegion().id?'selected':''}" data-state="${k}"><title>${esc(v15StateRegion(k)?.name||k)}</title></path></a>`).join('');
 const wp=store.get('waypoints',[]).filter(w=>Number.isFinite(w.lat)&&Number.isFinite(w.lon)&&w.lon>=5.5&&w.lon<=15.5&&w.lat>=47&&w.lat<=55.5).slice(-30);
 return `${pageTitle('Deutschland','Offline-Karte & GPS','Schon installiert: Übersicht über Deutschland mit allen 16 Bundesländern – kein Kartenimport nötig.')}
 <div class="notice warning"><b>Kartengrenze:</b> Dies ist eine vereinfachte <b>Bundesländer-Übersichtskarte</b>, keine Straßen-, Wanderweg-, Höhen- oder Rettungsnavigationskarte. Der GPS-Punkt ist eine ungefähre Lageanzeige; für Geländenavigation eine echte geprüfte Offline-Wanderkarte mitführen.</div>
 <div class="v15-mapbox"><div class="v15-map-toolbar"><button class="btn small" data-v15="gps">⌖ Meinen Standort</button><button class="btn secondary small" data-v15="gps-follow">◎ Live-GPS</button><button class="btn outline small" data-v15="map-reset">Übersicht</button></div>
 <div class="v15-map-area"><svg id="v15-map-svg" xmlns="http://www.w3.org/2000/svg" viewBox="${v15ViewBox()}" role="img" aria-label="Geografische Übersicht der deutschen Bundesländer, vereinfachte Grenzen">
 <rect x="-1000" y="-1000" width="3000" height="3000" fill="#0e2524"/>
 <g stroke="#39625a" stroke-width="0.8" opacity=".4">${Array.from({length:10},(_,i)=>`<path d="M${i*100},0V800M0,${i*100}H800"/>`).join('')}</g>
 ${shapes}
 ${wp.map(w=>`<circle cx="${(w.lon-5.5)*80}" cy="${(55.5-w.lat)*94}" r="7" fill="#efbc63" stroke="#102019" stroke-width="3"><title>${esc(w.name)}</title></circle>`).join('')}
 <g id="v15-my-position" style="display:none"><circle r="19" fill="#368fce" opacity=".22"/><circle r="8" fill="#4dc7ff" stroke="white" stroke-width="3"/></g>
 </svg><div class="v15-map-controls"><button type="button" data-v15="zoom-in" title="Vergrößern">+</button><button type="button" data-v15="zoom-out" title="Verkleinern">−</button></div></div>
 <div class="v15-map-footer"><span id="v15-gps-status">Standort noch nicht abgefragt</span><button class="btn secondary small" data-v15="gps-copy">Koordinaten kopieren</button></div></div>
 <p class="tiny muted">Quellenhinweis: Bundesländer-Grenzgeometrien vereinfacht nach <a href="https://github.com/isellsoap/deutschlandGeoJSON" target="_blank" rel="noopener noreferrer">DeutschlandGeoJSON (Public Domain/Unlicense)</a>; keine Straßen oder Live-Warnungen. GPS benötigt eine Standortfreigabe und ein Gerät mit Ortungsdiensten; Satelliten-GPS kann auch ohne Internet funktionieren, eine Positionsbestimmung ist aber nicht garantiert.</p>
 <div class="v15-map-shortcuts"><label for="v15-region-choice"><strong>Bundesland auswählen</strong></label><select id="v15-region-choice" aria-label="Bundesland auswählen">${states}</select><button class="btn" data-v15="region-open">Region öffnen →</button></div>
 <div class="section-title"><h2>Alle 16 Bundesländer</h2><a href="#/bundeslaender">Vollständige Liste →</a></div><div class="v15-map-regions">${(window.SURVIVAL_REGIONS||[]).map(r=>`<a href="#/bundesland/${r.id}">${esc(r.name)} →</a>`).join('')}</div>
 <div class="notice"><b>Eigene Wegpunkte und GPX-Dateien:</b> Deine bisherigen gespeicherten Wegpunkte bleiben erhalten. <a href="#/gpx">GPX-Viewer öffnen</a> · <a href="#/karten-alt">Alten Kartenbildimport</a></div>`;
}
function v15MapInit(){v15MapState.scale=1;v15MapState.centerX=405;v15MapState.centerY=405;}
function v15MapDraw(){let s=document.getElementById('v15-map-svg');if(s)s.setAttribute('viewBox',v15ViewBox());let m=document.getElementById('v15-my-position');if(m&&v15MapState.gps){m.setAttribute('transform',`translate(${(v15MapState.gps.lon-5.5)*80},${(55.5-v15MapState.gps.lat)*94})`);m.style.display='';}}
function v15GPSfollow(){const status=document.getElementById('v15-gps-status');if(!status)return;if(!navigator.geolocation){status.textContent='Keine Geolokalisierung verfügbar.';return}status.textContent='GPS wird angefragt …';navigator.geolocation.getCurrentPosition(p=>{const {latitude:lat,longitude:lon,accuracy}=p.coords;v15MapState.gps={lat,lon,accuracy};status.textContent=`${lat.toFixed(6)}° N · ${lon.toFixed(6)}° E · Genauigkeit ungefähr ${Math.round(accuracy)} m`;if(lon>=5.5&&lon<=15.5&&lat>=47&&lat<=55.5){v15MapState.centerX=(lon-5.5)*80;v15MapState.centerY=(55.5-lat)*94;v15MapState.scale=2.6;}else{status.textContent+=' · Außerhalb des Kartengebiets';}v15MapDraw();},e=>{status.textContent='GPS nicht verfügbar: Bitte Standortberechtigung prüfen oder im Freien erneut versuchen.'},{enableHighAccuracy:true,timeout:16000,maximumAge:5000});}
function v15ShelterList(){return `${pageTitle('Praktisches Überleben','10 Arten von Unterschlupf','Verständliche Materiallisten und Schrittfolgen für unterschiedliche Wetterlagen.')}
 <div class="notice warning">Vorrang hat immer eine sichere, erlaubte Unterkunft. Die Bilder sind KI-Szenen und keine geprüften Bauabnahmen. Übe nur mit Erlaubnis, nutze loses Material und beachte Sturm-, Hochwasser- und Waldschutzrisiken.</div>
 <div class="v15-photo-grid">${V15_SHELTERS.map(s=>`<a class="v15-tile" href="#/schutzbau/${s.id}">${pic(s.image,s.name)}<div><strong>${esc(s.name)}</strong><small>${esc(s.best)}</small><span>${s.steps.length} Schritte ansehen →</span></div></a>`).join('')}</div>`}
function v15ShelterDetail(id){const s=V15_SHELTERS.find(i=>i.id===id);if(!s)return notFound();return `<a class="back" href="#/unterschlupf">← Alle Unterschlüpfe</a>${pageTitle('Unterschlupf · Praxis',s.name,s.best)}${imageFigure(s.image,s.name)}<div class="v15-specs"><p><b>Übungszeit:</b> ${esc(s.time)}</p><p><b>Material:</b> ${s.materials.map(esc).join(' · ')}</p></div><h2>Schritt-für-Schritt</h2><ol class="v15-step-list">${s.steps.map((t,i)=>`<li><b>${i+1}</b><p>${esc(t)}</p></li>`).join('')}</ol><div class="notice warning"><b>Sicherheitskontrolle:</b> ${esc(s.caution)}</div><div class="notice">KI-Fotobeispiel des fertigen Aufbaus; einzelne Arbeitsschritte sind schriftlich erläutert, nicht einzeln fotografisch validiert.</div><a class="btn secondary" href="#/knotenschule">Knotenschule öffnen →</a>`}
function v15WildList(){return `${pageTitle('Wildtiere & Lebensmittel','Jagd, Wildhygiene & Zubereitung','Reh, Wildschwein, Feldhase und ausgewählte jagdbare Wildvögel.')}
 <div class="notice warning"><b>Rechtliches & Gesundheit:</b> Jagd ist in Deutschland an Jagdrecht, Jagdschein, Revierberechtigung, Artenschutz, Schonzeiten und Hygienevorschriften gebunden. Die Texte dienen zur Nachbereitung durch ausgebildete Berechtigte, nicht zur selbstständigen Jagd oder Wildtier-Tötung. Bei auffälligem Wild Abstand halten.</div>
 <div class="v15-photo-grid">${V15_WILD.map(w=>`<a class="v15-tile" href="#/wildart/${w.id}">${pic(w.image,w.name)}<div><strong>${esc(w.name)}</strong><small>${esc(w.facts)}</small><span>${w.steps.length} Arbeitsschritte & Rezept →</span></div></a>`).join('')}</div><div class="notice">Diese Bilder sind KI-generierte Symbol- und Motivbilder, keine verifizierte Anleitung für einzelne Schnitte. Für fachgerechtes Aufbrechen/Ausnehmen und die Fleischuntersuchung ist praktische Ausbildung notwendig.</div>`}
function v15WildDetail(id){const w=V15_WILD.find(x=>x.id===id);if(!w)return notFound();const done=store.get('v15-wild:'+id,[]);return `<a class="back" href="#/wild">← Alle Wildarten</a>${pageTitle('Jagd, Wildbrethygiene & Küche',w.name,w.latin)}${imageFigure(w.image,w.name)}
 <div class="notice"><b>Vorkommen und Lebensweise:</b> ${esc(w.facts)}<p><b>Spuren:</b> ${esc(w.traces)}</p></div>
 <div class="notice danger"><strong>Wichtige Gesundheitsregel:</strong> ${esc(w.warning)}</div>
 <div class="section-title"><h2>7 Arbeitsschritte</h2><span class="pill">${w.steps.length} Schritte</span></div><div class="v15-wild-steps">${w.steps.map(([label,body,image],i)=>`<section class="v15-wild-step">${pic(image,label)}<div><div class="eyebrow">Schritt ${i+1} / 7</div><h3>${esc(label)}</h3><p>${esc(body)}</p><label class="v15-complete"><input type="checkbox" data-v15-wild="${esc(w.id)}" data-index="${i}" ${done.includes(i)?'checked':''}> Als gelesen markieren</label></div></section>`).join('')}</div>
 <div class="v15-recipe"><h2>Fleischteile</h2><p>${w.pieces.map(esc).join(' · ')}</p><h2>Zubereitungsidee</h2>${pic('kochen','KI-Fotobeispiel einer Waldküche')}<p>${esc(w.cook)}</p><div class="notice warning"><strong>Keine sichere Lebensmittelzubereitung ohne:</strong> bestätigte Wildfreigabe, saubere Geräte, durchgängige Kühlung und zuverlässig überprüften Garzustand. Wilde Krankheitserreger können ohne äußere Zeichen vorliegen.</div></div>
 <a class="btn secondary" href="#/wissen/9">Grundkapitel Wildhygiene →</a>`}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-v15]');if(!b)return;const a=b.dataset.v15;
 if(a==='gps'){v15GPSfollow();return}
 if(a==='gps-follow'){if(v15MapState.gpsWatch!==null){navigator.geolocation.clearWatch(v15MapState.gpsWatch);v15MapState.gpsWatch=null;b.textContent='◎ Live-GPS';return}v15GPSfollow();if(navigator.geolocation){v15MapState.gpsWatch=navigator.geolocation.watchPosition(p=>{v15MapState.gps={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy};v15MapDraw();const s=document.getElementById('v15-gps-status');if(s)s.textContent=p.coords.latitude.toFixed(6)+'° N · '+p.coords.longitude.toFixed(6)+'° E';},()=>{}, {enableHighAccuracy:true,maximumAge:5000});b.textContent='■ GPS stoppen';}return}
 if(a==='zoom-in'||a==='zoom-out'){v15MapState.scale=Math.max(1,Math.min(8,v15MapState.scale*(a==='zoom-in'?1.55:1/1.55)));v15MapDraw();return}
 if(a==='map-reset'){v15MapState.scale=1;v15MapState.centerX=405;v15MapState.centerY=405;v15MapDraw();return}
 if(a==='region-open'){const code=document.getElementById('v15-region-choice')?.value;if(code)location.hash='#/bundesland/'+encodeURIComponent(code);return}
 if(a==='gps-copy'){if(!v15MapState.gps){toast('Zuerst GPS-Position bestimmen');return}try{await navigator.clipboard.writeText(v15MapState.gps.lat.toFixed(6)+', '+v15MapState.gps.lon.toFixed(6));toast('Koordinaten kopiert')}catch(e){toast('Kopieren nicht verfügbar – Koordinaten auf Karte ablesen')}return}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-v15-wild]')){const id=e.target.dataset.v15Wild;const all=[...document.querySelectorAll('[data-v15-wild]')].filter(x=>x.checked).map(x=>Number(x.dataset.index));store.set('v15-wild:'+id,all);}});
window.addEventListener('hashchange',()=>{if(v15MapState.gpsWatch!==null){navigator.geolocation?.clearWatch(v15MapState.gpsWatch);v15MapState.gpsWatch=null}});
